name: knightassist_mobile_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  routemaster: ^1.0.1
  go_router: ^11.1.4
  url_strategy: ^0.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  custom_lint: ^0.5.3

flutter:
  uses-material-design: true