name: knightassist_mobile_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  go_router: ^11.1.4
  url_strategy: ^0.2.0
  http: ^1.1.0
  percent_indicator: "^4.0.1"
  editable_image: ^2.0.0
  intl: ^0.18.1
  photo_manager: ^3.0.0-dev.2
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.2
  objectid: ^3.0.0
  settings_ui: ^2.0.2
  mobile_scanner: ^3.5.5
  qr_code_scanner: ^1.0.1
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.0

flutter:
  uses-material-design: true
  assets: 
    - assets/KnightAssistCoATransparent.png
    - assets/KnightAssistCoA2.png
    - assets/KnightAssistCoA3.png
    - assets/example.png
    - assets/profile pictures/icon_apple.png
    - assets/profile pictures/icon_cat.png
    - assets/profile pictures/icon_cookie.png
    - assets/profile pictures/icon_controller.png
    - assets/profile pictures/icon_heart.png
    - assets/profile pictures/icon_leaf.png
    - assets/profile pictures/icon_musicnote.png
    - assets/profile pictures/icon_paintbrush.png
    - assets/profile pictures/icon_planet.png
    - assets/profile pictures/icon_soccer.png
    - assets/profile pictures/icon_weight.png
    - assets/icon/icon.png
    - assets/icon/icontransparent.png
    - assets/orgdefaultbackground.png
  fonts:
    - family: League Spartan
      fonts:
       - asset: fonts/LeagueSpartan-VariableFont_wght.ttf

flutter_icons:
  ios: "AppIcon"
  image_path_ios: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"