name: knightassist_mobile_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  go_router: ^11.1.4
  url_strategy: ^0.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  custom_lint: ^0.5.3

flutter:
  uses-material-design: true
  assets: 
    - assets/KnightAssistCoATransparent.png
    - assets/KnightAssistCoA2.png
    - assets/KnightAssistCoA3.png
    - assets/example.png
    - assets/profile pictures/icon_apple.png
    - assets/profile pictures/icon_cat.png
    - assets/profile pictures/icon_cookie.png
    - assets/profile pictures/icon_controller.png
    - assets/profile pictures/icon_heart.png
    - assets/profile pictures/icon_leaf.png
    - assets/profile pictures/icon_musicnote.png
    - assets/profile pictures/icon_paintbrush.png
    - assets/profile pictures/icon_planet.png
    - assets/profile pictures/icon_soccer.png
    - assets/profile pictures/icon_weight.png
    - assets/icon/icon.png
    - assets/icon/icontransparent.png
  fonts:
    - family: League Spartan
      fonts:
       - asset: fonts/LeagueSpartan-VariableFont_wght.ttf

flutter_icons:
  ios: "AppIcon"
  image_path_ios: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"